# Generated by Django 5.1.4 on 2026-04-22 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Базовая ставка, %')),
            ],
            options={
                'verbose_name': 'страховой продукт',
                'verbose_name_plural': 'страховые продукты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, unique=True, verbose_name='Номер полиса')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('premium', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Страховая премия')),
                ('insured_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Страховая сумма')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('expired', 'Истек'), ('cancelled', 'Расторгнут')], default='active', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='insurance.client', verbose_name='Клиент')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='insurance.insuranceproduct', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'полис',
                'verbose_name_plural': 'полисы',
                'ordering': ['-created_at', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_date', models.DateField(verbose_name='Дата случая')),
                ('description', models.TextField(verbose_name='Описание')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма ущерба')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_review', 'На рассмотрении'), ('approved', 'Одобрен'), ('rejected', 'Отклонен'), ('paid', 'Выплачен')], default='new', max_length=16, verbose_name='Статус')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='insurance.policy', verbose_name='Полис')),
            ],
            options={
                'verbose_name': 'страховой случай',
                'verbose_name_plural': 'страховые случаи',
                'ordering': ['-claim_date'],
            },
        ),
    ]
